# User config
author: "Cristina Verdi"
tagline: "Reflexiones desde las trincheras"
description: "Reflexiones desde las trincheras"
email: "cristina.verdi.tobon@gmail.com"
linkedin: "https://www.linkedin.com/in/cristina-verdi/"
twitter: "https://twitter.com/cristina_verdi"
github: "https://github.com/cristinaverdi"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed