# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings
title: Cristina Verdi | Drafts & Notes
email: cristina.verdi.tobon@gmail.com
author: Cristina Verdi
keywords: "Software Engineering, Technology, Product Development"
description: A Human Being.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "es"
url: "https://cristinaverdi.github.io" # the base hostname & protocol for your site
twitter_username: cristina_verdi
github_username: cristinaverdi
disqus_username:


# Build settings
markdown: kramdown
permalink: /:categories/:title/


# Posts settings
future: true
safe: true
lsi: false
excerpt_separator: "\n\n"


# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
